# Generated by Django 4.2.13 on 2024-06-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trassir', '0002_rename_login_nvr_uesrname_nvr_sdk_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nvr',
            name='ip',
            field=models.CharField(max_length=100),
        ),
    ]
