# Generated by Django 4.2.13 on 2024-06-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trassir', '0004_alter_nvr_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nvr',
            old_name='uesrname',
            new_name='username',
        ),
    ]
