# Generated by Django 4.2.13 on 2024-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trassir', '0006_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='collected_at',
            field=models.DateTimeField(),
        ),
    ]
