# Generated by Django 4.2.13 on 2024-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trassir', '0007_alter_health_collected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nvr',
            name='ip',
            field=models.CharField(max_length=100),
        ),
    ]
